version: 2
sources:
  - name: wordpress_sources
    database: raw
    schema: wordpress
    tables:
      - name: categories
      - name: media
      - name: pages
      - name: posts
      - name: search
      - name: tags
      - name: users
      - name: fivetran_audit
        freshness: 
          warn_after: {count: 24, period: hour}
          error_after: {count: 25, period: hour}
        loaded_at_field: _fivetran_synced  